name: firebase_login
description: Authorization logic using firebase developed for Ocnus;

version: 1.0.0+1

environment:
  sdk: ">=2.5.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  logger: ^0.8.2
  equatable: ^1.0.2
  flutter_bloc: ^3.1.0
  bloc: ^3.0.0
  firebase_core: ^0.4.4
  google_sign_in: ^4.1.1
  firebase_auth: ^0.15.4
  meta: ^1.1.8
  font_awesome_flutter: ^8.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  effective_dart: ^1.2.1
  hive_generator: ^0.7.0
  build_runner: ^1.7.3
  bloc_test: ^3.0.1

  mockito: ^4.1.0

flutter:
  uses-material-design: true
