name: oknos
description: Oknos offers tools for businesses renting differnt types of items. It was developed for costume tentals but can be easily extended to suit other purposes.

version: 1.0.0+1

environment:
  sdk: ">=2.5.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.1.8
  flutter_bloc: ^3.1.0
  bloc: ^3.0.0
  logger: ^0.8.2
  font_awesome_flutter: ^8.5.0
  hive: ^1.3.0
  hive_flutter: ^0.3.0

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^0.7.0
  build_runner: ^1.7.3

  bloc_test: ^3.0.1

  mockito: ^4.1.0

flutter:
  uses-material-design: true