name: ocnus
description: Ocnus offers tools for businesses renting differnt types of items. It was developed for costume tentals but can be easily extended to suit other purposes.

version: 1.0.0+1

environment:
  sdk: ">=2.5.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.1.8
  rentables:
    path: rentables
  font_awesome_flutter: ^8.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  effective_dart: ^1.2.1

  mockito: ^4.1.0

flutter:
  uses-material-design: true