name: oknos
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.1.8
  equatable: ^1.0.2
  flutter_bloc: ^3.1.0
  bloc: ^3.0.0
  logger: ^0.8.2

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  bloc_test: ^3.0.1

  mockito: ^4.1.0

flutter:
  uses-material-design: true