name: rentables
description: Collection of database and business logic for objects developed for Ocnus;

version: 1.0.0+1

environment:
  sdk: ">=2.5.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.1.8
  logger: ^0.8.2
  font_awesome_flutter: ^8.5.0
  hive: ^1.3.0
  hive_flutter: ^0.3.0
  uuid: ^2.0.4
  equatable: ^1.0.2
  flutter_bloc: ^3.1.0
  bloc: ^3.0.0
  dns: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  effective_dart: ^1.2.1
  hive_generator: ^0.7.0
  build_runner: ^1.7.3
  bloc_test: ^3.0.1

  mockito: ^4.1.0

flutter:
  uses-material-design: true