name: CI

on: [push]

jobs:
  Ocnus-CI:
    name: Rentables
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      #Set-Up environment
      - uses: subosito/flutter-action@v1
        with:
          channel: 'dev'
    #Run Flutter Tests
      - name: Run Flutter tests
        working-directory: ./rentables
        run: |
          sudo chmod 777 -R *
          flutter pub get
          flutter test --coverage .
          cat coverage/lcov.info >> ../coverage/lcov.info
      - name: Godacov
        uses: brpaz/godacov-action@v1.0.3
        with:
          reportPath: '../coverage/lcov.info'
          codacyToken: ${{ secrets.CODACY_PROJECT_TOKEN }}
          commitId: ${{ github.sha }}
      #Dart/Flutter package analyzer
      - name: Dart Analysis
        uses: axel-op/dart-package-analyzer/with-full-sdk@stable
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          minAnnotationLevel: info
