name: CI

on: [push]

jobs:
  test-frontend:
    name: Ocnus CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      #Set-Up enviorment
      - uses: subosito/flutter-action@v1
        with:
          channel: 'dev'
    #Run Flutter Tests
      - run: sudo chmod 777 -R *
      - run: flutter pub get
      - run: flutter test --coverage
      #CodeCov
      - name: CodeCov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage/lcov.info
          fail_ci_if_error: true
      #Dart/Flutter package analyzer
      - name: Dart Analysis
        uses: axel-op/dart-package-analyzer/with-full-sdk@stable
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          minAnnotationLevel: info
